### ISSUE TITLE
Global Settings

### ISSUE THREAD

**Issue by hercase** [hifrontendcafe/website#72]
La manera de implementar las configuraciones desde backend no es la mas optima ya que la index page recibe static props y hace prop drilling hacia los demas componentes. 

Necesitamos una solucion que solo haga una peticion y la data sea accesible desde cualquier parte del proyecto, algo similar a un state global pero con SSG.

Esto nos permitirá incorporar mas opciones de configuraciones dinamicas.

Info util:
https://github.com/vercel/next.js/discussions/10909#discussioncomment-1250
https://www.netlify.com/blog/2020/12/01/using-react-context-for-state-management-in-next.js/

**Comment by marbiano** [comment]
@hercase podriamos explorar usar `react-query` en [su integracion con Next.js](https://react-query.tanstack.com/guides/ssr).

**Comment by agusmar** [comment]
@Fedeya este issue ya queda cerrado con lo que hiciste el sábado?

**Comment by Fedeya** [comment]
> @Fedeya este issue ya queda cerrado con lo que hiciste el sábado?

Si me olvide linkear el pr
