### ISSUE TITLE
Hero img isn't responsive

### ISSUE THREAD

**Issue by agusmar** [hifrontendcafe/website#87]
Hero img isn't responsive

**Design**
![image](https://user-images.githubusercontent.com/44821883/113631064-3fa7ce00-963f-11eb-9b8a-5987b25f3234.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/44821883/113630795-d58f2900-963e-11eb-823c-84d766c73f89.png)

**Comment by hercase** [comment]
![image](https://user-images.githubusercontent.com/5130752/113639937-b0a3b180-9650-11eb-9ca6-8c18f08a899b.png)

Could it be an alternative?

**Comment by agusmar** [comment]
Hmmm I'm not sure, I'd rather hide the img and just leave the animated titles 💜
